namespace: ansilab
name: hoop
version: 1.0.0
authors:
- Jan-Piet Mens <jp@mens.de> (https://jpmens.net)
description: >
  This is an demonstration collection for my Ansible trainings, and it's called
  _hoop_ because the EE is called _wheel_. (Nobody is assumed to understand
  that. ;-)
license:
- GPL-2.0-or-later
tags: [ ansilab, demo, example, testing ]
dependencies: {}
repository: https://github.com/jpmens/ansilab-hoop
documentation: https://github.com/jpmens/ansilab-hoop/README.md
readme: https://github.com/jpmens/ansilab-hoop/README.md
homepage: https://github.com/jpmens/ansilab-hoop
issues: https://github.com/jpmens/ansilab-hoop/issues

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
build_ignore: 
  - _jp_upload.sh

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null

